# Generated by Django 5.2.6 on 2025-09-24 18:05

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=64, verbose_name='Make')),
                ('model', models.CharField(max_length=64, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text='Year of manufacture', verbose_name='Year')),
                ('engine_type', models.CharField(max_length=64, verbose_name='Engine type')),
                ('fuel_type', models.CharField(blank=True, choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('L', 'LPG'), ('H', 'Hybrid'), ('E', 'Electric')], help_text='Type of engine power', max_length=1, verbose_name='Fuel')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('description', models.TextField(max_length=2048, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_no', models.CharField(blank=True, max_length=16, null=True, verbose_name='License plate No')),
                ('vin_code', models.CharField(max_length=17, verbose_name='VIN code')),
                ('client_name', models.CharField(max_length=64, verbose_name="Client's name")),
                ('observations', tinymce.models.HTMLField()),
                ('photo', models.ImageField(default='car_photos/no_photo.png', upload_to='car_photos/')),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='finalapp.carmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Order creation date', verbose_name='Date')),
                ('status', models.CharField(choices=[('0', 'New'), ('1', 'Declined'), ('2', 'Accepted'), ('3', 'Waiting'), ('4', 'In progress'), ('5', 'Completed')], default='0', help_text='Order status', max_length=1, verbose_name='Status')),
                ('deadline', models.DateTimeField(help_text='Order finish date & time', verbose_name='Deadline')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='finalapp.car', verbose_name='Car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics', verbose_name='Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finalapp.order', verbose_name='Order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finalapp.service', verbose_name='Service')),
            ],
        ),
    ]
